### ISSUE TITLE
web3-provider doesn't work with custom rpc

### ISSUE THREAD

**Issue by Shirikatsu** [Web3Modal/web3modal#282]
`"@walletconnect/web3-provider": "^1.4.1"`

Following the docs [here](https://docs.walletconnect.org/quick-start/dapps/web3-provider#setup) I attempted the following:

```typescript
import WalletConnectProvider from "@walletconnect/web3-provider";

...

const provider = new WalletConnectProvider({
    rpc: {  
        56: "https://bsc-dataseed.binance.org",
    },
});

await provider.enable();
```

The QR modal pops up and I scan using TrustWallet and I get errors:

```javascript
Unhandled Promise rejection: Callback was already called. ; Zone: <root> ; Task: Promise.then ; Value: Error: Callback was already called.
    at onlyOnce.js:9
    at createAsyncMiddleware.js:54
    at ZoneDelegate.invoke (zone-evergreen.js:372)
    at Zone.run (zone-evergreen.js:134)
    at zone-evergreen.js:1276
    at ZoneDelegate.invokeTask (zone-evergreen.js:406)
    at Zone.runTask (zone-evergreen.js:178)
    at drainMicroTaskQueue (zone-evergreen.js:582) Error: Callback was already called.
    at http://localhost:4200/vendor.js:165943:32
    at http://localhost:4200/vendor.js:97:11
    at ZoneDelegate.invoke (http://localhost:4200/polyfills.js:1146:26)
    at Zone.run (http://localhost:4200/polyfills.js:908:43)
    at http://localhost:4200/polyfills.js:2050:36
    at ZoneDelegate.invokeTask (http://localhost:4200/polyfills.js:1180:31)
    at Zone.runTask (http://localhost:4200/polyfills.js:952:47)
    at drainMicroTaskQueue (http://localhost:4200/polyfills.js:1356:35)
```

and clear querying against infura mainnet even though a node url was provided:

<img width="615" alt="Screenshot 2021-06-03 at 17 43 06" src="https://user-images.githubusercontent.com/4716816/120681331-29798b00-c493-11eb-8cd3-73e45a349513.png">

What am I doing wrong?

**Comment by Shirikatsu** [comment]
Somehow I've submitted this to the completely wrong project. Apologies!!!!
